// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgE8Fupl4ZlxAa0ainF9eSNtyr_oqAQzY',
    appId: '1:18356463525:web:64d68349fd15887d11ea4c',
    messagingSenderId: '18356463525',
    projectId: 'chat-app-flutter-96582',
    authDomain: 'chat-app-flutter-96582.firebaseapp.com',
    storageBucket: 'chat-app-flutter-96582.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATwAFqRdAqRTvwEShBT6FTMgJBKnd2GuU',
    appId: '1:18356463525:android:9bca97ab9ce1a63611ea4c',
    messagingSenderId: '18356463525',
    projectId: 'chat-app-flutter-96582',
    storageBucket: 'chat-app-flutter-96582.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaIY38xtBzD8ow3zkXNVTHoe9DPMNjmoc',
    appId: '1:18356463525:ios:051be545a110f58511ea4c',
    messagingSenderId: '18356463525',
    projectId: 'chat-app-flutter-96582',
    storageBucket: 'chat-app-flutter-96582.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCaIY38xtBzD8ow3zkXNVTHoe9DPMNjmoc',
    appId: '1:18356463525:ios:051be545a110f58511ea4c',
    messagingSenderId: '18356463525',
    projectId: 'chat-app-flutter-96582',
    storageBucket: 'chat-app-flutter-96582.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAgE8Fupl4ZlxAa0ainF9eSNtyr_oqAQzY',
    appId: '1:18356463525:web:64d68349fd15887d11ea4c',
    messagingSenderId: '18356463525',
    projectId: 'chat-app-flutter-96582',
    authDomain: 'chat-app-flutter-96582.firebaseapp.com',
    storageBucket: 'chat-app-flutter-96582.firebasestorage.app',
  );
}
